/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as StockRouteImport } from './routes/stock'
import { Route as EstimatorRouteImport } from './routes/estimator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogueModelIdRouteImport } from './routes/catalogue_.$modelId'
import { Route as Char91_devChar93UiRouteImport } from './routes/[_dev].ui'
import { Route as Char91_devChar93EstimatorStatesRouteImport } from './routes/[_dev].estimator-states'
import { Route as Char91_devChar93DashboardStatesRouteImport } from './routes/[_dev].dashboard-states'
import { Route as Char91_devChar93AppshellRouteImport } from './routes/[_dev].appshell'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatorRoute = EstimatorRouteImport.update({
  id: '/estimator',
  path: '/estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueModelIdRoute = CatalogueModelIdRouteImport.update({
  id: '/catalogue_/$modelId',
  path: '/catalogue/$modelId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_devChar93UiRoute = Char91_devChar93UiRouteImport.update({
  id: '/_dev/ui',
  path: '/_dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_devChar93EstimatorStatesRoute =
  Char91_devChar93EstimatorStatesRouteImport.update({
    id: '/_dev/estimator-states',
    path: '/_dev/estimator-states',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91_devChar93DashboardStatesRoute =
  Char91_devChar93DashboardStatesRouteImport.update({
    id: '/_dev/dashboard-states',
    path: '/_dev/dashboard-states',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91_devChar93AppshellRoute =
  Char91_devChar93AppshellRouteImport.update({
    id: '/_dev/appshell',
    path: '/_dev/appshell',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/dashboard': typeof DashboardRoute
  '/estimator': typeof EstimatorRoute
  '/stock': typeof StockRoute
  '/watchlist': typeof WatchlistRoute
  '/_dev/appshell': typeof Char91_devChar93AppshellRoute
  '/_dev/dashboard-states': typeof Char91_devChar93DashboardStatesRoute
  '/_dev/estimator-states': typeof Char91_devChar93EstimatorStatesRoute
  '/_dev/ui': typeof Char91_devChar93UiRoute
  '/catalogue/$modelId': typeof CatalogueModelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/dashboard': typeof DashboardRoute
  '/estimator': typeof EstimatorRoute
  '/stock': typeof StockRoute
  '/watchlist': typeof WatchlistRoute
  '/_dev/appshell': typeof Char91_devChar93AppshellRoute
  '/_dev/dashboard-states': typeof Char91_devChar93DashboardStatesRoute
  '/_dev/estimator-states': typeof Char91_devChar93EstimatorStatesRoute
  '/_dev/ui': typeof Char91_devChar93UiRoute
  '/catalogue/$modelId': typeof CatalogueModelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogue': typeof CatalogueRoute
  '/dashboard': typeof DashboardRoute
  '/estimator': typeof EstimatorRoute
  '/stock': typeof StockRoute
  '/watchlist': typeof WatchlistRoute
  '/_dev/appshell': typeof Char91_devChar93AppshellRoute
  '/_dev/dashboard-states': typeof Char91_devChar93DashboardStatesRoute
  '/_dev/estimator-states': typeof Char91_devChar93EstimatorStatesRoute
  '/_dev/ui': typeof Char91_devChar93UiRoute
  '/catalogue_/$modelId': typeof CatalogueModelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/catalogue'
    | '/dashboard'
    | '/estimator'
    | '/stock'
    | '/watchlist'
    | '/_dev/appshell'
    | '/_dev/dashboard-states'
    | '/_dev/estimator-states'
    | '/_dev/ui'
    | '/catalogue/$modelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalogue'
    | '/dashboard'
    | '/estimator'
    | '/stock'
    | '/watchlist'
    | '/_dev/appshell'
    | '/_dev/dashboard-states'
    | '/_dev/estimator-states'
    | '/_dev/ui'
    | '/catalogue/$modelId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/catalogue'
    | '/dashboard'
    | '/estimator'
    | '/stock'
    | '/watchlist'
    | '/_dev/appshell'
    | '/_dev/dashboard-states'
    | '/_dev/estimator-states'
    | '/_dev/ui'
    | '/catalogue_/$modelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CatalogueRoute: typeof CatalogueRoute
  DashboardRoute: typeof DashboardRoute
  EstimatorRoute: typeof EstimatorRoute
  StockRoute: typeof StockRoute
  WatchlistRoute: typeof WatchlistRoute
  Char91_devChar93AppshellRoute: typeof Char91_devChar93AppshellRoute
  Char91_devChar93DashboardStatesRoute: typeof Char91_devChar93DashboardStatesRoute
  Char91_devChar93EstimatorStatesRoute: typeof Char91_devChar93EstimatorStatesRoute
  Char91_devChar93UiRoute: typeof Char91_devChar93UiRoute
  CatalogueModelIdRoute: typeof CatalogueModelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimator': {
      id: '/estimator'
      path: '/estimator'
      fullPath: '/estimator'
      preLoaderRoute: typeof EstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue_/$modelId': {
      id: '/catalogue_/$modelId'
      path: '/catalogue/$modelId'
      fullPath: '/catalogue/$modelId'
      preLoaderRoute: typeof CatalogueModelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/ui': {
      id: '/_dev/ui'
      path: '/_dev/ui'
      fullPath: '/_dev/ui'
      preLoaderRoute: typeof Char91_devChar93UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/estimator-states': {
      id: '/_dev/estimator-states'
      path: '/_dev/estimator-states'
      fullPath: '/_dev/estimator-states'
      preLoaderRoute: typeof Char91_devChar93EstimatorStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/dashboard-states': {
      id: '/_dev/dashboard-states'
      path: '/_dev/dashboard-states'
      fullPath: '/_dev/dashboard-states'
      preLoaderRoute: typeof Char91_devChar93DashboardStatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/appshell': {
      id: '/_dev/appshell'
      path: '/_dev/appshell'
      fullPath: '/_dev/appshell'
      preLoaderRoute: typeof Char91_devChar93AppshellRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CatalogueRoute: CatalogueRoute,
  DashboardRoute: DashboardRoute,
  EstimatorRoute: EstimatorRoute,
  StockRoute: StockRoute,
  WatchlistRoute: WatchlistRoute,
  Char91_devChar93AppshellRoute: Char91_devChar93AppshellRoute,
  Char91_devChar93DashboardStatesRoute: Char91_devChar93DashboardStatesRoute,
  Char91_devChar93EstimatorStatesRoute: Char91_devChar93EstimatorStatesRoute,
  Char91_devChar93UiRoute: Char91_devChar93UiRoute,
  CatalogueModelIdRoute: CatalogueModelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
