/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91_devChar93UiRouteImport } from './routes/[_dev].ui'
import { Route as Char91_devChar93AppshellPartsRouteImport } from './routes/[_dev].appshell-parts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_devChar93UiRoute = Char91_devChar93UiRouteImport.update({
  id: '/_dev/ui',
  path: '/_dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_devChar93AppshellPartsRoute =
  Char91_devChar93AppshellPartsRouteImport.update({
    id: '/_dev/appshell-parts',
    path: '/_dev/appshell-parts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_dev/appshell-parts': typeof Char91_devChar93AppshellPartsRoute
  '/_dev/ui': typeof Char91_devChar93UiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_dev/appshell-parts': typeof Char91_devChar93AppshellPartsRoute
  '/_dev/ui': typeof Char91_devChar93UiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_dev/appshell-parts': typeof Char91_devChar93AppshellPartsRoute
  '/_dev/ui': typeof Char91_devChar93UiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/_dev/appshell-parts' | '/_dev/ui'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/_dev/appshell-parts' | '/_dev/ui'
  id: '__root__' | '/' | '/auth' | '/_dev/appshell-parts' | '/_dev/ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  Char91_devChar93AppshellPartsRoute: typeof Char91_devChar93AppshellPartsRoute
  Char91_devChar93UiRoute: typeof Char91_devChar93UiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/ui': {
      id: '/_dev/ui'
      path: '/_dev/ui'
      fullPath: '/_dev/ui'
      preLoaderRoute: typeof Char91_devChar93UiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/appshell-parts': {
      id: '/_dev/appshell-parts'
      path: '/_dev/appshell-parts'
      fullPath: '/_dev/appshell-parts'
      preLoaderRoute: typeof Char91_devChar93AppshellPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  Char91_devChar93AppshellPartsRoute: Char91_devChar93AppshellPartsRoute,
  Char91_devChar93UiRoute: Char91_devChar93UiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
